Levi Hayes Lab 6/Models/CandyModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BusinessObjects;


namespace Levi_Hayes_Lab_6.Models
{
    public class CandyModel
    {
        public List<Candy> CandyList { get; set; }

        [DisplayName("Candy Name")]
        [Required(ErrorMessage ="Please enter a name of a candy")]
        public string CandyName { get; set; }
    }
}

Levi Hayes Lab 6/Models/CostumeModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BusinessObjects;


namespace Levi_Hayes_Lab_6.Models
{
    public class CostumeModel
    {
        public List<Costume> CostumeList { get; set; }

        [DisplayName("Costume Name")]
        [Required(ErrorMessage = "Please enter a name of a costume")]
        public string CostumeName { get; set; }
    }
}

Levi Hayes Lab 6/Models/ErrorViewModel.cs
using System;

namespace Levi_Hayes_Lab_6.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Levi Hayes Lab 6/Models/TreaterModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BusinessObjects;


namespace Levi_Hayes_Lab_6.Models
{
    public class TreaterModel
    {
        public List<Treater> TreaterList { get; set; }
        public List<Candy> CandyList { get; set; }
        public List<Costume> CostumeList { get; set; }


        public int TreaterID;

        [Required(ErrorMessage = "Treater needs a name")]
        [DisplayName("Treater's Name")]
        public string TreaterName { get; set; }

        [Required(ErrorMessage ="Treater needs a favorite Candy")]
        [DisplayName("Treater's Favorite Candy")]
        [UIHint("CandyDropdown")]
        public int CandyID { get; set; }
        public string CandyName { get; set; }

        [Required(ErrorMessage = "Treater needs a costume")]
        [DisplayName("Treater's costume")]
        [UIHint("CostumeDropdown")]
        public int CostumeID { get; set; }
        public string CostumeName { get; set; }
    }
}

Levi Hayes Lab 6/Controllers/CandyController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BusinessObjects;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using Levi_Hayes_Lab_6.Models;
using Levi_Hayes_Lab_6.Repositories;
using Levi_Hayes_Lab_6.ExtensionMethods;

namespace Levi_Hayes_Lab_6.Controllers
{
    public class CandyController : Controller
    {
        private ICandyRepository _CandyRepo;
        public CandyController(ICandyRepository candyRepo)
        {
            _CandyRepo = candyRepo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            CandyModel model = new CandyModel();
            model.CandyList = _CandyRepo.GetList();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CandyModel model)
        {
            Candy candy = new Candy();
            candy.productName = model.CandyName;
            _CandyRepo.Insert(candy);
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            _CandyRepo.Delete(id);
            return RedirectToAction("Index");

        }
    }
}

Levi Hayes Lab 6/Controllers/CostumeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BusinessObjects;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using Levi_Hayes_Lab_6.Models;
using Levi_Hayes_Lab_6.Repositories;
using Levi_Hayes_Lab_6.ExtensionMethods;

namespace Levi_Hayes_Lab_6.Controllers
{
    public class CostumeController : Controller
    {
        private ICostumeRepository _CostumeRepo;
        public CostumeController(ICostumeRepository costumeRepo)
        {
            _CostumeRepo = costumeRepo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            CostumeModel model = new CostumeModel();
            model.CostumeList = _CostumeRepo.GetList();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CostumeModel model)
        {
            Costume costume = new Costume();
            costume.costume = model.CostumeName;
            _CostumeRepo.Insert(costume);
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            _CostumeRepo.Delete(id);
            return RedirectToAction("Index");

        }
    }
}

Levi Hayes Lab 6/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BusinessObjects;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using Levi_Hayes_Lab_6.Models;
using Levi_Hayes_Lab_6.Repositories;
using Levi_Hayes_Lab_6.ExtensionMethods;
using System.Diagnostics;

namespace Levi_Hayes_Lab_6.Controllers
{
    public class HomeController : Controller
    {
        private ITreaterRepository _TreaterRepository;
        private ICandyRepository _CandyRepository;
        private ICostumeRepository _CostumeRepository;
        public HomeController(ITreaterRepository treaterRepository, ICandyRepository candyRepository, ICostumeRepository costumeRepository)
        {
            _TreaterRepository = treaterRepository;
            _CandyRepository = candyRepository;
            _CostumeRepository = costumeRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            TreaterModel model = new TreaterModel();
            model.TreaterList = _TreaterRepository.GetList();
            model.CandyList = _CandyRepository.GetList();
            model.CostumeList = _CostumeRepository.GetList();
            return View(model);
        }
        [HttpPost]
        public IActionResult Create(TreaterModel model)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Index", model);

            model.CostumeName = _CostumeRepository.GetList().Select(m => m).First(m => m.id == model.CostumeID).costume;
            model.CandyName = _CandyRepository.GetList().Select(m => m).First(m => m.id == model.CandyID).productName;
           
            _TreaterRepository.Insert(model.GetTreaterObject());
            return RedirectToAction("Index");

        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Levi Hayes Lab 6/Views/Candy/Index.cshtml
@model CandyModel

@{
    ViewData["Title"] = "Home Page";
}

<body>
    <form method="post" asp-action="Create" asp-controller="Candy">
        <div class="row">
            <div class="form-group col-sm-4">
                <label asp-for="CandyName" class="control-label"></label>
                <input asp-for="CandyName" class="form-control" />
                <span asp-validation-for="CandyName" class="text-danger"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-default" value="Model">Create</button>
    </form>
    <br />
    <div>
        <h2>Current Treaters</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var candy in Model.CandyList)
                {
                    <tr>
                        <td>
                            @candy.productName
                        </td>
                        <td>
                            <form method="post" asp-action="Delete" asp-controller="Candy">
                                @Html.AntiForgeryToken()
                                <input type="hidden" name="id" value="@candy.id" />
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</body>

Levi Hayes Lab 6/Views/Costume/Index.cshtml
@model CostumeModel

@{
    ViewData["Title"] = "Home Page";
}

<body>
    <form method="post" asp-action="Create" asp-controller="Costume">
        <div class="row">
            <div class="form-group col-sm-4">
                <label asp-for="CostumeName" class="control-label"></label>
                <input asp-for="CostumeName" class="form-control" />
                <span asp-validation-for="CostumeName" class="text-danger"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-default" value="Model">Create</button>
    </form>
    <br />
    <div>
        <h2>Current Treaters</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var costume in Model.CostumeList)
                {
                    <tr>
                        <td>
                            @costume.costume
                        </td>
                        <td>
                            <form method="post" asp-action="Delete" asp-controller="Costume">
                                @Html.AntiForgeryToken()
                                <input type="hidden" name="id" value="@costume.id" />
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</body>

Levi Hayes Lab 6/Views/Home/Index.cshtml
@model TreaterModel

@{
    ViewData["Title"] = "Home Page";
}

<body>
    <form method="post" asp-action="Create" asp-controller="Home">
        <div class="row">
            <div class="form-group col-sm-4">
                <label asp-for="TreaterName" class="control-label"></label>
                <input asp-for="TreaterName" class="form-control" />
                <span asp-validation-for="TreaterName" class="text-danger"></span>
            </div>
            <div class="form-group col-sm-4">
                <label asp-for="CandyID" class="control-label"></label>
                <select asp-for="CandyID" asp-items="@(new SelectList(Model.CandyList, "id", "productName"))" class="form-control"></select>
                <span asp-validation-for="CandyID" class="text-danger"></span>
            </div>
            <div class="form-group col-sm-4">
                <label asp-for="CostumeID" class="control-label"></label>
                <select asp-for="CostumeID" asp-items="@(new SelectList(Model.CostumeList, "id", "costume"))" class="form-control"></select>
                <span asp-validation-for="CostumeID" class="text-danger"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-default" value="Model">Create</button>
    </form>
    <br />
    <div>
        <h2>Current Treaters</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Favorite Candy</th>
                    <th scope="col">Costume</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var treater in Model.TreaterList)
                {
                    <tr>
                        <td>
                            @treater.name
                        </td>
                        <td>
                            @treater.favoriteCandy.productName
                        </td>
                        <td>
                            @treater.costume.costume
                        </td>
                        <td>
                            @*<form method="post" asp-action="Delete" asp-controller="Home">
                                @Html.AntiForgeryToken()
                                <input type="hidden" name="id" value="@treater.id" />
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>*@
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</body>

Levi Hayes Lab 6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Levi Hayes</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    @*<link rel="Stylesheet" href="/css/site.css" type="text/css" />*@
    <link rel="Stylesheet" href="/css/default.css" type="text/css" />
</head>
<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark navbar-static-top">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a asp-controller="Home" asp-action="Index" class="nav-link">Treaters</a>
            </li>
            <li class="nav-item active">
                <a asp-controller="Candy" asp-action="Index" class="nav-link">Candy</a>
            </li>
            <li class="nav-item active">
                <a asp-controller="Costume" asp-action="Index" class="nav-link">Costumes</a>
            </li>
        </ul>
    </nav>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Levi Hayes Lab 6</p>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>